# Generated by Django 2.2.9 on 2020-01-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodReads', '0002_auto_20200122_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntuacion',
            old_name='idLibro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='puntuacion',
            old_name='idUsuario',
            new_name='usuario',
        ),
    ]
